/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "9.5.0"
    id("com.gradleup.shadow") version "9.6.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.fancyinnovations.com/releases")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.de.oliver.fancyholograms)
    implementation("org.bstats:bstats-bukkit:3.2.1")
}

group = "dev.mizio.mcPlugins"
version = "1.2.1"
description = "Wyświetlanie nazw itemów na półkach."
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    project.configurations.runtimeClasspath.map { setOf(it) }.also { configurations = it }

    dependencies {
        // Only merge bStats into the final jar, no other dependencies
        exclude { it.moduleGroup != "org.bstats" }
    }

    // Relocate bStats into the plugin's package to avoid conflicts with other
    // plugins using bStats
    relocate("org.bstats", project.group.toString())
}

tasks.processResources {
    val props = mapOf(
        "version" to project.version,
        "name" to project.name,
        "description" to (project.description ?: "")
    )

    inputs.properties(props)

    filesMatching(listOf("plugin.yml")) {
        expand(props)
    }
}
