/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "9.5.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.fancyinnovations.com/releases")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.de.oliver.fancyholograms)
}

group = "dev.mizio.mcPlugins"
version = "1.2.0"
description = "Wyświetlanie nazw itemów na półkach."
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.processResources {
    val props = mapOf(
        "version" to project.version,
        "name" to project.name,
        "description" to (project.description ?: "")
    )

    inputs.properties(props)

    filesMatching(listOf("plugin.yml")) {
        expand(props)
    }
}
