name: ${name}
version: ${version}
main: dev.mizio.mcPlugins.shelfNames.MainShelfNames
api-version: '1.21'
authors: [ 'MizPablito' ]
description: ${description}

softdepend:
 - FancyHolograms

commands:
  shelfnames:
    usage: /shelfnames clear
    description: Zarządzanie hologramami ShelfNames
    permissions:
      shelfnames.clear:
        default: op
permissions:
  shelfnames.clear:
    description: Uprawnienie do usuwania hologramów ShelfNames
    default: op