name: ${name}
version: ${version}
main: dev.mizio.mcPlugins.shelfNames.MainShelfNames
api-version: '1.21'
authors: [ 'MizPablito' ]
description: ${description}
website: https://github.com/mizpablito/ShelfNames

softdepend:
 - FancyHolograms

commands:
  shelfnames:
    usage: /shelfnames [info|clear|reload]
    description: Informacje o pluginie oraz komendy administracyjne ShelfNames

permissions:
  shelfnames.admin:
    description: Pełny dostęp do komend ShelfNames (clear, reload)
    default: op
